2019-11-23 20:36:03,702 - ERROR - ERROR - {'position': 'cpu', 'cmd': './blade create cpu fullload', 'ip': u'192.168.199.41'}
2019-11-23 20:36:03,704 - INFO - 127.0.0.1 - - [23/Nov/2019 20:36:03] "POST /tool/api/v1.0/chaosblade/inject-cpu HTTP/1.1" 200 -
2019-11-23 20:37:37,109 - INFO -  * Detected change in '/Users/yagotoasa/Documents/Course/\xe8\xbd\xaf\xe4\xbb\xb6\xe5\xb7\xa5\xe7\xa8\x8b/K8s/github-repository/2019-XLab-KubernetesTools/services/fault_injector.py', reloading
2019-11-23 20:45:26,709 - ERROR - UNREACHABLE - {'msg': u'Failed to connect to the host via ssh: OpenSSH_7.9p1, LibreSSL 2.7.3\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 48: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 192.168.199.41 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket "/Users/yagotoasa/.ansible/cp/ffcbe6c9e6" does not exist\r\ndebug1: Executing proxy command: exec ssh -o ConnectTimeout=6000000 -p 20022 root@10.60.38.181 nc -w 100000 192.168.199.41 22\r\ndebug3: timeout: 10000 ms remain after connect\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_rsa type 0\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_rsa-cert type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_dsa type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_dsa-cert type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_ecdsa type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_ecdsa-cert type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_ed25519 type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_ed25519-cert type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_xmss type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_xmss-cert type -1\r\ndebug1: Local version string SSH-2.0-OpenSSH_7.9\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@10.60.38.181: Permission denied (publickey,password).\r\nssh_exchange_identification: Connection closed by remote host', 'ip': u'192.168.199.41', 'cmd': './blade create cpu fullload', 'position': 'cpu'}
2019-11-23 20:45:26,710 - INFO - 127.0.0.1 - - [23/Nov/2019 20:45:26] "POST /tool/api/v1.0/chaosblade/inject-cpu HTTP/1.1" 200 -
2019-11-23 20:48:25,226 - INFO -  * Detected change in '/Users/yagotoasa/Documents/Course/\xe8\xbd\xaf\xe4\xbb\xb6\xe5\xb7\xa5\xe7\xa8\x8b/K8s/github-repository/2019-XLab-KubernetesTools/services/fault_injector.py', reloading
2019-11-23 20:48:43,812 - ERROR - UNREACHABLE - {'ip': u'192.168.199.41', 'message': u'Failed to connect to the host via ssh: OpenSSH_7.9p1, LibreSSL 2.7.3\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 48: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 192.168.199.41 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket "/Users/yagotoasa/.ansible/cp/ffcbe6c9e6" does not exist\r\ndebug1: Executing proxy command: exec ssh -o ConnectTimeout=6000000 -p 20022 root@10.60.38.181 nc -w 100000 192.168.199.41 22\r\ndebug3: timeout: 10000 ms remain after connect\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_rsa type 0\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_rsa-cert type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_dsa type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_dsa-cert type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_ecdsa type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_ecdsa-cert type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_ed25519 type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_ed25519-cert type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_xmss type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_xmss-cert type -1\r\ndebug1: Local version string SSH-2.0-OpenSSH_7.9\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@10.60.38.181: Permission denied (publickey,password).\r\nssh_exchange_identification: Connection closed by remote host', 'cmd': './blade create cpu fullload', 'position': 'cpu'}
2019-11-23 20:48:43,814 - INFO - 127.0.0.1 - - [23/Nov/2019 20:48:43] "POST /tool/api/v1.0/chaosblade/inject-cpu HTTP/1.1" 200 -
2019-11-23 20:49:56,605 - INFO -  * Detected change in '/Users/yagotoasa/Documents/Course/\xe8\xbd\xaf\xe4\xbb\xb6\xe5\xb7\xa5\xe7\xa8\x8b/K8s/github-repository/2019-XLab-KubernetesTools/services/fault_injector.py', reloading
2019-11-23 21:23:59,421 - ERROR - UNREACHABLE - {'ip': u'192.168.199.41', 'message': u'Failed to connect to the host via ssh: OpenSSH_7.9p1, LibreSSL 2.7.3\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 48: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 192.168.199.41 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket "/Users/yagotoasa/.ansible/cp/ffcbe6c9e6" does not exist\r\ndebug1: Executing proxy command: exec ssh -o ConnectTimeout=6000000 -p 20022 root@10.60.38.181 nc -w 100000 192.168.199.41 22\r\ndebug3: timeout: 10000 ms remain after connect\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_rsa type 0\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_rsa-cert type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_dsa type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_dsa-cert type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_ecdsa type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_ecdsa-cert type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_ed25519 type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_ed25519-cert type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_xmss type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_xmss-cert type -1\r\ndebug1: Local version string SSH-2.0-OpenSSH_7.9\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@10.60.38.181: Permission denied (publickey,password).\r\nssh_exchange_identification: Connection closed by remote host', 'cmd': u'./blade create cpu fullload --timeout 60', 'position': 'cpu'}
2019-11-23 21:23:59,422 - INFO - 127.0.0.1 - - [23/Nov/2019 21:23:59] "POST /tool/api/v1.0/chaosblade/inject-cpu HTTP/1.1" 200 -
2019-11-23 21:24:24,830 - INFO - 127.0.0.1 - - [23/Nov/2019 21:24:24] "POST /tool/api/v1.0/chaosblade/inject-cpu HTTP/1.1" 500 -
2019-11-23 21:25:01,248 - INFO -  * Detected change in '/Users/yagotoasa/Documents/Course/\xe8\xbd\xaf\xe4\xbb\xb6\xe5\xb7\xa5\xe7\xa8\x8b/K8s/github-repository/2019-XLab-KubernetesTools/services/fault_injector.py', reloading
2019-11-23 21:26:24,150 - ERROR - UNREACHABLE - {'ip': u'192.168.199.45', 'message': u'Failed to connect to the host via ssh: OpenSSH_7.9p1, LibreSSL 2.7.3\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 48: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 192.168.199.45 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket "/Users/yagotoasa/.ansible/cp/17b43c6c0e" does not exist\r\ndebug1: Executing proxy command: exec ssh -o ConnectTimeout=6000000 -p 20022 root@10.60.38.181 nc -w 100000 192.168.199.45 22\r\ndebug3: timeout: 10000 ms remain after connect\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_rsa type 0\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_rsa-cert type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_dsa type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_dsa-cert type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_ecdsa type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_ecdsa-cert type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_ed25519 type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_ed25519-cert type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_xmss type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_xmss-cert type -1\r\ndebug1: Local version string SSH-2.0-OpenSSH_7.9\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@10.60.38.181: Permission denied (publickey,password).\r\nssh_exchange_identification: Connection closed by remote host', 'cmd': u'./blade create cpu fullload --timeout 60', 'position': 'cpu'}
2019-11-23 21:26:24,151 - INFO - 127.0.0.1 - - [23/Nov/2019 21:26:24] "POST /tool/api/v1.0/chaosblade/inject-cpu HTTP/1.1" 200 -
2019-11-23 21:27:54,760 - INFO -  * Detected change in '/Users/yagotoasa/Documents/Course/\xe8\xbd\xaf\xe4\xbb\xb6\xe5\xb7\xa5\xe7\xa8\x8b/K8s/github-repository/2019-XLab-KubernetesTools/utils/log_record.py', reloading
2019-11-23 21:30:42,787 - ERROR - UNREACHABLE - {'ip': u'192.168.199.41', 'message': u'Failed to connect to the host via ssh: OpenSSH_7.9p1, LibreSSL 2.7.3\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 48: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 192.168.199.41 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket "/Users/yagotoasa/.ansible/cp/ffcbe6c9e6" does not exist\r\ndebug1: Executing proxy command: exec ssh -o ConnectTimeout=6000000 -p 20022 root@10.60.38.181 nc -w 100000 192.168.199.41 22\r\ndebug3: timeout: 10000 ms remain after connect\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_rsa type 0\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_rsa-cert type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_dsa type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_dsa-cert type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_ecdsa type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_ecdsa-cert type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_ed25519 type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_ed25519-cert type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_xmss type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_xmss-cert type -1\r\ndebug1: Local version string SSH-2.0-OpenSSH_7.9\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@10.60.38.181: Permission denied (publickey,password).\r\nssh_exchange_identification: Connection closed by remote host', 'cmd': u'./blade create disk burn --read --timeout 60', 'position': 'disk'}
2019-11-23 21:30:42,789 - INFO - 127.0.0.1 - - [23/Nov/2019 21:30:42] "POST /tool/api/v1.0/chaosblade/inject-disk HTTP/1.1" 200 -
2019-11-23 21:31:34,955 - INFO -  * Detected change in '/Users/yagotoasa/Documents/Course/\xe8\xbd\xaf\xe4\xbb\xb6\xe5\xb7\xa5\xe7\xa8\x8b/K8s/github-repository/2019-XLab-KubernetesTools/services/fault_injector.py', reloading
2019-11-23 21:41:39,421 - ERROR - {'command info': {'host': u'192.168.199.47', 'type': u'read', 'timeout': u'60'}, 'message': u'Host: 192.168.199.47 does not exist.'}
2019-11-23 21:41:39,422 - INFO - 127.0.0.1 - - [23/Nov/2019 21:41:39] "POST /tool/api/v1.0/chaosblade/inject-disk HTTP/1.1" 200 -
2019-11-23 21:43:48,935 - INFO -  * Detected change in '/Users/yagotoasa/Documents/Course/\xe8\xbd\xaf\xe4\xbb\xb6\xe5\xb7\xa5\xe7\xa8\x8b/K8s/github-repository/2019-XLab-KubernetesTools/services/fault_injector.py', reloading
2019-11-23 22:51:03,362 - ERROR - HOST NOT EXIST - {'command info': {'host': u'192.168.199.47'}, 'message': u'Host: 192.168.199.47 does not exist.'}
2019-11-23 22:51:03,363 - INFO - 127.0.0.1 - - [23/Nov/2019 22:51:03] "POST /tool/api/v1.0/chaosblade/stop-all-inject-on-target-host HTTP/1.1" 200 -
2019-11-23 22:51:15,955 - INFO -  * Detected change in '/Users/yagotoasa/Documents/Course/\xe8\xbd\xaf\xe4\xbb\xb6\xe5\xb7\xa5\xe7\xa8\x8b/K8s/github-repository/2019-XLab-KubernetesTools/services/fault_injector.py', reloading
2019-11-23 22:53:59,834 - ERROR - HOST NOT EXIST - {'command info': {'host': u'192.168.199.47'}, 'message': u'Host: 192.168.199.47 does not exist.'}
2019-11-23 22:53:59,835 - INFO - 127.0.0.1 - - [23/Nov/2019 22:53:59] "POST /tool/api/v1.0/chaosblade/stop-all-inject-on-target-host HTTP/1.1" 200 -
2019-11-23 22:54:13,550 - INFO - 127.0.0.1 - - [23/Nov/2019 22:54:13] "POST /tool/api/v1.0/chaosblade/stop-all-inject-on-target-host HTTP/1.1" 200 -
2019-11-23 22:55:57,519 - INFO -  * Detected change in '/Users/yagotoasa/Documents/Course/\xe8\xbd\xaf\xe4\xbb\xb6\xe5\xb7\xa5\xe7\xa8\x8b/K8s/github-repository/2019-XLab-KubernetesTools/services/fault_injector.py', reloading
2019-11-23 23:09:52,621 - ERROR - UNREACHABLE - {'ip': u'192.168.199.41', 'message': u'Failed to connect to the host via ssh: OpenSSH_7.9p1, LibreSSL 2.7.3\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 48: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 192.168.199.41 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket "/Users/yagotoasa/.ansible/cp/ffcbe6c9e6" does not exist\r\ndebug1: Executing proxy command: exec ssh -o ConnectTimeout=6000000 -p 20022 root@10.60.38.181 nc -w 100000 192.168.199.41 22\r\ndebug3: timeout: 10000 ms remain after connect\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_rsa type 0\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_rsa-cert type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_dsa type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_dsa-cert type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_ecdsa type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_ecdsa-cert type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_ed25519 type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_ed25519-cert type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_xmss type -1\r\ndebug1: identity file /Users/yagotoasa/.ssh/id_xmss-cert type -1\r\ndebug1: Local version string SSH-2.0-OpenSSH_7.9\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@10.60.38.181: Permission denied (publickey,password).\r\nssh_exchange_identification: Connection closed by remote host', 'cmd': u'./blade create cpu fullload --timeout 60', 'position': 'cpu'}
2019-11-23 23:09:52,622 - INFO - 127.0.0.1 - - [23/Nov/2019 23:09:52] "POST /tool/api/v1.0/chaosblade/inject-cpu HTTP/1.1" 200 -
2019-11-23 23:14:25,551 - ERROR - UID NOT FOUND - {'cmd': u'./blade destroy c64c4dbac05dedae'}
2019-11-23 23:14:25,551 - INFO - 127.0.0.1 - - [23/Nov/2019 23:14:25] "POST /tool/api/v1.0/chaosblade/stop-specific-inject HTTP/1.1" 200 -
2019-11-23 23:14:46,792 - INFO -  * Detected change in '/Users/yagotoasa/Documents/Course/\xe8\xbd\xaf\xe4\xbb\xb6\xe5\xb7\xa5\xe7\xa8\x8b/K8s/github-repository/2019-XLab-KubernetesTools/services/fault_injector.py', reloading
2019-11-23 23:14:51,986 - ERROR - UID NOT FOUND - {'cmd': u'./blade destroy c64c4dbac05dedae'}
2019-11-23 23:14:51,987 - INFO - 127.0.0.1 - - [23/Nov/2019 23:14:51] "POST /tool/api/v1.0/chaosblade/stop-specific-inject HTTP/1.1" 200 -
2019-11-23 23:15:34,575 - INFO -  * Detected change in '/Users/yagotoasa/Documents/Course/\xe8\xbd\xaf\xe4\xbb\xb6\xe5\xb7\xa5\xe7\xa8\x8b/K8s/github-repository/2019-XLab-KubernetesTools/services/fault_injector.py', reloading
